### ISSUE TITLE
Congrats, and Questions about the F1

### ISSUE THREAD

**Issue by harryhaaren** [crepererum/tf1d#1]
Hey!

This is cool: I'm thinking about getting an F1, but I'm not sure. I google linux support, see your post on the NI forum with a link to your reverse-engineered work: congrats, awesome!

Are the pads "soft" and sensitive, or more Akai MPD type "hit-me-really-hard"? I have an Akai MPD32 now, and can't use it proberly because the pads dont' respond lightly-enough for me...

If I was to aquire an F1, i would be interested in helping finishing the LED output code, since that's the other reason I'm replacing the MPD.

Hope you don't mind me filing an issue asking questions about the device :)
Cheers, -Harry

**Comment by crepererum** [comment]
I don't know how the pads of the MPD are, but I can describe you the F1 ones: They are digital pads and you need to push them to get a click. When removing the finger they click back. So they feel quite hard. They're intended to be used as a sample-starter and not as a drum machine (like the Machine equipment) or as analog pads (like the Ableton Push). NI developed the F1 for their Traktor software and you get a good impression for what it was designed for when watching their advertisement videos.

**Comment by harryhaaren** [comment]
Cleaning up my Github issue tracker - closing this - thanks for the answer! To make a long story short, I've been working on a C library for accessing USB controllers like the F1, it might be of interest: https://github.com/openAVproductions/openAV-ctlra
