### ISSUE TITLE
Can you help me I cannot build/make/install

### ISSUE THREAD

**Issue by Luxcium** [crepererum/tf1d#2]
```
make build
sudo make install
mkdir -p target
cc -std=gnu99 -O2 -lasound -lusb-1.0 -pthread -o target/tf1d tf1d.c
tf1d.c:10:10: erreur fatale: alsa/asoundlib.h : Aucun fichier ou dossier de ce type
   10 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminée.
make: *** [Makefile:10: target/tf1d] Error 1
mkdir -p target
cc -std=gnu99 -O2 -lasound -lusb-1.0 -pthread -o target/tf1d tf1d.c
tf1d.c:10:10: erreur fatale: alsa/asoundlib.h : Aucun fichier ou dossier de ce type
   10 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminée.
make: *** [Makefile:10: target/tf1d] Error 1

```

**Comment by Luxcium** [comment]
alsa-firmware.noarch                                                                  1.2.1-7.fc32                                                        @fedora               
alsa-lib.x86_64                                                                       1.2.3.2-1.fc32                                                      @updates              
alsa-plugins-jack.x86_64                                                              1.2.2-1.fc32                                                        @fedora               
alsa-plugins-pulseaudio.x86_64                                                        1.2.2-1.fc32                                                        @fedora               
alsa-plugins-samplerate.x86_64                                                        1.2.2-1.fc32                                                        @fedora               
alsa-plugins-upmix.x86_64                                                             1.2.2-1.fc32                                                        @fedora               
alsa-plugins-usbstream.x86_64                                                         1.2.2-1.fc32                                                        @fedora               
alsa-plugins-vdownmix.x86_64                                                          1.2.2-1.fc32                                                        @fedora               
alsa-sof-firmware.noarch                                                              1.5-1.fc32                                                          @updates              
alsa-tools.x86_64                                                                     1.2.2-1.fc32                                                        @fedora               
alsa-tools-firmware.x86_64                                                            1.2.2-1.fc32                                                        @fedora               
alsa-ucm.noarch                                                                       1.2.3.2-1.fc32                                                      @updates              
alsa-utils.x86_64                                                                     1.2.3-4.fc32                                                        @updates              
alsamixergui.x86_64                                                                   0.9.0-0.30.rc2.fc32                                                 @fedora               
python3-alsa.x86_64                                                                   1.1.6-10.fc32                                                       @fedora               
qemu-audio-alsa.x86_64                                                                2:4.2.1-1.fc32                                                      @updates              
zita-alsa-pcmi.x86_64                                                                 0.3.2-2.fc32                                                        @fedora

**Comment by Luxcium** [comment]
libusb.x86_64                                                                              1:0.1.5-16.fc32                                                               @fedora
libusbmuxd.x86_64                                                                          2.0.0-2.fc32                                                                  @fedora
libusbx.x86_64                                                                             1.0.23-1.fc32                                                                 @fedora

**Comment by crepererum** [comment]
You're likely missing the development libraries (something like `alsa-lib-devel`).

**Comment by Luxcium** [comment]
> You're likely missing the development libraries (something like `alsa-lib-devel`).

**Thanks @crepererum** 

![Screenshot_20201012_191410](https://user-images.githubusercontent.com/42672814/95798180-40c6f680-0cbf-11eb-8e48-6c2ea32aa506.png)

**Comment by Luxcium** [comment]
So when I list the midi Midi Port Names I get: 

```
Through:Midi Through Port-0 14:0
Komplete Audio 6:Komplete Audio 6 MIDI 1 32:0
Client-131:Virtual RawMIDI 131:0
```

After plugging/unplugging the *F1* I now know that it is ***'Client-131:Virtual RawMIDI 131:0'***   

![Screenshot_20201012_194529](https://user-images.githubusercontent.com/42672814/95799750-a4532300-0cc3-11eb-8786-3a9ebeb18c69.png)

**Comment by Luxcium** [comment]
I didn't know what software to use to monitor the inputs...  But I finally used my favorite programing language in the world and *HURRAY!!!* it's working 

![Screenshot_20201012_195341](https://user-images.githubusercontent.com/42672814/95800109-a669b180-0cc4-11eb-9005-0f21abb4d661.png)

**Comment by Luxcium** [comment]
can you point me in a direction if possible in regard to having the lights working somehow?

**Comment by crepererum** [comment]
For the lights: I had it working at some point but lost the source code. IIRC, that involved some USB fuzzing and a bunch of hours of work. 😉

**Comment by Luxcium** [comment]
can you point me in any direction for the lights, please?


I have decided to go JavaScript because I am more fluent in that language using [node-midi](https://www.npmjs.com/package/midi) I don't know if you have any idea how I can for sure select the F1 because it doesn't have a named item in the list and I am not sure if I can relate to `Client-128:Virtual RawMIDI 128:0` as the name of the device ina ll scenarios

is the [*Manufacturer SysEx ID Numbers*](https://www.midi.org/specifications-old/item/manufacturer-id-numbers) is useful for something?

[Native Instruments](http://www.native-instruments.de/) **00H 21H 09H**

**Comment by crepererum** [comment]
Lights are currently not implemented and need some substantial work both on the protocol side (i.e. to understand what the device expects) and and the implementation side (i.e. listening for midi signals, transcoding and sending it to the device).
